name: Docker Image CI

on:
  push:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code
      
    - name: "setting the commit sha in environment variable"
    - run: echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - run : echo "${{env.commit}}"

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: munnakumar/helloworld
        tags: ${{env.commit}}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
